/*
 * secplus_receiver.h
 *
 * ESPHome component class for Security+ 2.0 decoding.
 *
 * Wraps ManchesterDecoder (secplus_shim.h) as a proper ESPHome Component so
 * that:
 *   - Sensor wiring is handled in C++ setup(), not in user lambdas.
 *   - Users only need to call  id(my_receiver).process(x)  from the
 *     remote_receiver on_raw lambda; no on_boot wiring needed.
 *   - Both sensors are optional: declare only the ones you need in YAML.
 *
 * Generated by __init__.py via:
 *   var = cg.new_Pvariable(config[CONF_ID])
 *   cg.add(var.set_remote_id_sensor(sens))
 *   cg.add(var.set_rolling_code_sensor(sens))
 */

#pragma once

#include "esphome/core/component.h"
#include "esphome/components/text_sensor/text_sensor.h"
#include "secplus_shim.h"   // ManchesterDecoder, SecplusResult

namespace esphome {
namespace secplus_receiver {

class SecplusReceiverComponent : public Component {
 public:
  // ── Sensor setters (called from generated main.cpp) ──────────────────────
  void set_remote_id_sensor(text_sensor::TextSensor *s)    { remote_id_sensor_    = s; }
  void set_rolling_code_sensor(text_sensor::TextSensor *s) { rolling_code_sensor_ = s; }

  // ── ESPHome lifecycle ─────────────────────────────────────────────────────
  void setup() override {
    decoder_.on_result([this](const SecplusResult &r) {
      this->on_decode_result_(r);
    });
  }

  float get_setup_priority() const override {
    // Run after hardware (GPIO / SPI) is ready, before network.
    return setup_priority::DATA;
  }

  // ── Public API ────────────────────────────────────────────────────────────
  /**
   * process()
   *
   * Feed raw pulse durations from the remote_receiver on_raw lambda.
   * Call from YAML like:
   *
   *   on_raw:
   *     - lambda: id(my_receiver).process(x);
   *
   * Accepts any container whose value_type is convertible to int
   * (std::vector<int32_t> from remote_receiver, etc.).
   */
  template <typename Container>
  void process(const Container &pulses) {
    decoder_.process(pulses);
  }

 protected:
  ManchesterDecoder decoder_;
  text_sensor::TextSensor *remote_id_sensor_    = nullptr;
  text_sensor::TextSensor *rolling_code_sensor_ = nullptr;

  void on_decode_result_(const SecplusResult &r) {
    char buf[24];

    if (remote_id_sensor_ != nullptr) {
      snprintf(buf, sizeof(buf), "%llu", (unsigned long long)r.remote_id);
      remote_id_sensor_->publish_state(buf);
    }

    if (rolling_code_sensor_ != nullptr) {
      snprintf(buf, sizeof(buf), "%d", (int)r.rolling);
      rolling_code_sensor_->publish_state(buf);
    }

    ESP_LOGD("secplus",
             "remote_id=%llu  rolling=%d  data=0x%08X  frame_type=%u",
             (unsigned long long)r.remote_id,
             (int)r.rolling,
             (unsigned)r.data,
             (unsigned)r.frame_type);
  }
};

}  // namespace secplus_receiver
}  // namespace esphome
